// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHUyknniEc_FtouhgKCIuGt-MYG-KNkjI',
    appId: '1:545457065698:web:ea9bf435e961351dbb18bb',
    messagingSenderId: '545457065698',
    projectId: 'tcf-preparation',
    authDomain: 'tcf-preparation.firebaseapp.com',
    storageBucket: 'tcf-preparation.firebasestorage.app',
    measurementId: 'G-HQ0KB4TLF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEA7IxiT-R4CucW1Vmg4UR8qwcGdmgQzU',
    appId: '1:545457065698:android:676cc9514ed8ccb0bb18bb',
    messagingSenderId: '545457065698',
    projectId: 'tcf-preparation',
    storageBucket: 'tcf-preparation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqSTchafg6NKAuT3Bh2LLbnUhN6h_9ILc',
    appId: '1:545457065698:ios:e5224cd8b3fb1f34bb18bb',
    messagingSenderId: '545457065698',
    projectId: 'tcf-preparation',
    storageBucket: 'tcf-preparation.firebasestorage.app',
    iosBundleId: 'com.tcfcan.tcfCanadaPreparation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHUyknniEc_FtouhgKCIuGt-MYG-KNkjI',
    appId: '1:545457065698:web:0921678a63d99ce3bb18bb',
    messagingSenderId: '545457065698',
    projectId: 'tcf-preparation',
    authDomain: 'tcf-preparation.firebaseapp.com',
    storageBucket: 'tcf-preparation.firebasestorage.app',
    measurementId: 'G-11ZNFMRBZV',
  );
}
